In [10]:
import pandas as pd
import pickle
from tensorflow.keras.models import load_model

In [ ]:
X_test = pd.read_csv('X_test')
Y_test = pd.read_csv('Y_test')

In [11]:
with open('label_encoder_sex.pkl','rb') as file:
    label_encoder_sex = pickle.load(file)

with open('label_encoder_smoke.pkl','rb') as file:
    label_encoder_smoke = pickle.load(file)

with open('onehot_region.pkl','rb') as file:
    onehot_region = pickle.load(file)    

with open('scalar.pkl','rb') as file:
    scalar = pickle.load(file)

In [12]:
X_test['sex'] = label_encoder_sex.transform(X_test['sex'])

In [13]:
X_test

     age  sex     bmi  children smoker     region
0     45    0  25.175         2     no  northeast
1     36    0  30.020         0     no  northwest
2     64    0  26.885         0    yes  northwest
3     46    1  25.745         3     no  northwest
4     19    1  31.920         0    yes  northwest
..   ...  ...     ...       ...    ...        ...
263   63    1  35.090         0    yes  southeast
264   58    0  27.170         0     no  northwest
265   38    1  28.025         1     no  northeast
266   54    0  47.410         0    yes  southeast
267   51    0  34.200         1     no  southwest

[268 rows x 6 columns]