In [10]:
import pandas as pd
import pickle
from tensorflow.keras.models import load_model

In [11]:
# Loading the dataset
X_test = pd.read_csv('X_test')
X_test_copy = X_test.copy()
Y_test = pd.read_csv('Y_test')

In [12]:
# Loading the necessary encoders, scalars, model
with open('label_encoder_sex.pkl','rb') as file:
    label_encoder_sex = pickle.load(file)

with open('label_encoder_smoke.pkl','rb') as file:
    label_encoder_smoke = pickle.load(file)

with open('onehot_region.pkl','rb') as file:
    onehot_region = pickle.load(file)    

with open('scalar.pkl','rb') as file:
    scalar = pickle.load(file)    

model = load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [13]:
# Label Encoding
X_test['sex'] = label_encoder_sex.transform(X_test['sex'])
X_test['smoker'] = label_encoder_smoke.transform(X_test['smoker'])

In [14]:
# One Hot Encoding
X_test_region = onehot_region.transform(X_test[['region']])
col_names = onehot_region.get_feature_names_out()
encoded_df_test = pd.DataFrame(X_test_region,columns = col_names )
X_test = X_test.drop('region',axis = 1)
X_test = pd.concat([X_test, encoded_df_test], axis = 1)

In [15]:
# Scaling
X_test = scalar.transform(X_test)

In [16]:
# Prediction
predict = model.predict(X_test)
predict

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

array([[10596.266 ],
       [ 6135.239 ],
       [33391.24  ],
       [ 9237.972 ],
       [28825.55  ],
       [ 8900.701 ],
       [ 3083.7996],
       [16870.773 ],
       [ 5636.531 ],
       [10995.178 ],
       [20756.04  ],
       [ 7589.5312],
       [ 4228.1523],
       [48371.89  ],
       [51023.066 ],
       [43749.273 ],
       [11991.734 ],
       [40583.926 ],
       [ 8749.175 ],
       [27782.977 ],
       [ 2587.2412],
       [ 8229.981 ],
       [ 1828.2139],
       [ 6594.8564],
       [11686.03  ],
       [12409.112 ],
       [15091.124 ],
       [ 7035.6963],
       [11196.229 ],
       [ 2001.8486],
       [ 7662.89  ],
       [12462.259 ],
       [ 3386.1675],
       [ 5237.6206],
       [ 1924.9109],
       [ 7879.6953],
       [ 2454.1372],
       [ 8070.0483],
       [27145.635 ],
       [36866.812 ],
       [ 4968.65  ],
       [ 4084.393 ],
       [13868.231 ],
       [13033.118 ],
       [ 6560.5977],
       [13665.838 ],
       [ 6155.7573],
       [ 2335.277 ],
       [39649.066 ],
       [ 6452.8135],
       [15449.452 ],
       [ 2378.5024],
       [10956.259 ],
       [ 2958.5386],
       [12339.737 ],
       [ 9964.632 ],
       [ 4854.6826],
       [36294.145 ],
       [14110.028 ],
       [12090.731 ],
       [15817.316 ],
       [ 7443.8696],
       [16228.977 ],
       [ 7583.7134],
       [11943.859 ],
       [ 4436.7363],
       [20363.027 ],
       [12325.981 ],
       [ 3953.8572],
       [ 4305.047 ],
       [ 6757.973 ],
       [11157.323 ],
       [ 9151.679 ],
       [ 7500.4575],
       [ 8995.559 ],
       [ 4959.075 ],
       [ 7035.4023],
       [11541.849 ],
       [ 4500.628 ],
       [ 8144.2393],
       [ 2242.3398],
       [34478.883 ],
       [ 3912.4507],
       [38099.953 ],
       [53984.33  ],
       [36594.566 ],
       [ 5462.91  ],
       [12094.442 ],
       [ 8794.809 ],
       [13003.313 ],
       [16756.309 ],
       [31833.398 ],
       [28495.635 ],
       [ 6824.4663],
       [36727.496 ],
       [ 7438.2075],
       [28499.105 ],
       [ 3066.232 ],
       [21235.777 ],
       [ 8683.69  ],
       [ 5027.162 ],
       [ 2715.6558],
       [ 7778.281 ],
       [14082.866 ],
       [12740.027 ],
       [ 2905.3542],
       [ 9117.577 ],
       [26245.662 ],
       [ 3266.12  ],
       [27140.236 ],
       [ 2142.773 ],
       [ 7714.656 ],
       [14013.615 ],
       [32568.762 ],
       [11514.94  ],
       [ 2330.406 ],
       [12698.936 ],
       [27984.916 ],
       [ 6223.412 ],
       [ 4111.3374],
       [ 8140.3633],
       [ 8569.471 ],
       [13085.196 ],
       [ 2979.4204],
       [ 4702.637 ],
       [ 8734.261 ],
       [ 7952.8545],
       [ 9244.465 ],
       [13846.719 ],
       [ 3673.9722],
       [ 4534.9307],
       [ 7613.8916],
       [ 6758.689 ],
       [10114.93  ],
       [ 7034.193 ],
       [14853.819 ],
       [ 5103.9463],
       [34287.324 ],
       [44493.793 ],
       [31717.97  ],
       [ 6188.2676],
       [11481.628 ],
       [ 3185.575 ],
       [14424.03  ],
       [ 3538.585 ],
       [29658.342 ],
       [ 5262.87  ],
       [ 4410.8164],
       [14413.428 ],
       [ 5087.4854],
       [44998.938 ],
       [ 3427.9204],
       [ 3036.9875],
       [33822.836 ],
       [10226.171 ],
       [ 5281.6416],
       [13531.496 ],
       [ 9072.017 ],
       [28840.875 ],
       [34423.812 ],
       [14617.106 ],
       [ 3577.6418],
       [15218.366 ],
       [ 3817.1375],
       [ 3000.718 ],
       [ 9120.347 ],
       [50561.473 ],
       [37310.484 ],
       [33991.242 ],
       [ 3461.1997],
       [ 9320.464 ],
       [ 6883.78  ],
       [ 9567.426 ],
       [ 4645.08  ],
       [ 2864.5598],
       [28220.328 ],
       [23477.541 ],
       [16358.251 ],
       [15431.767 ],
       [11790.949 ],
       [36400.336 ],
       [ 5452.328 ],
       [ 8800.405 ],
       [ 5179.898 ],
       [ 7175.113 ],
       [ 4381.0186],
       [ 5530.5835],
       [ 4086.9954],
       [11737.537 ],
       [11654.909 ],
       [ 4657.76  ],
       [ 4510.695 ],
       [ 5084.986 ],
       [37747.68  ],
       [15027.074 ],
       [10408.636 ],
       [ 3560.7825],
       [13217.074 ],
       [ 4600.849 ],
       [10290.804 ],
       [ 4145.682 ],
       [30707.062 ],
       [ 7310.5894],
       [ 4292.1836],
       [21693.537 ],
       [20730.854 ],
       [ 9915.47  ],
       [ 4947.54  ],
       [ 9578.68  ],
       [ 2378.5984],
       [14260.994 ],
       [13981.295 ],
       [16361.492 ],
       [24701.182 ],
       [ 8250.476 ],
       [ 6486.3716],
       [ 4951.565 ],
       [14526.534 ],
       [15253.664 ],
       [ 5479.609 ],
       [ 4978.3887],
       [11198.853 ],
       [11674.6   ],
       [41797.625 ],
       [ 3996.3403],
       [30713.643 ],
       [ 1982.6514],
       [ 3544.9368],
       [10790.083 ],
       [14256.295 ],
       [ 2703.075 ],
       [ 9519.698 ],
       [ 2880.8726],
       [31952.293 ],
       [ 9731.4795],
       [ 9382.089 ],
       [ 5119.5273],
       [ 8202.775 ],
       [43885.92  ],
       [ 2524.393 ],
       [13955.144 ],
       [35954.73  ],
       [ 4932.3364],
       [ 3771.0989],
       [ 3304.0615],
       [ 4030.5166],
       [ 3025.738 ],
       [ 4089.1448],
       [19832.145 ],
       [ 3241.1233],
       [ 2880.4841],
       [ 7841.438 ],
       [ 3493.3213],
       [13191.472 ],
       [ 4479.3877],
       [ 3658.5725],
       [14287.481 ],
       [ 4985.25  ],
       [ 8902.315 ],
       [ 9747.14  ],
       [ 8371.029 ],
       [13156.113 ],
       [27443.805 ],
       [45926.234 ],
       [12345.851 ],
       [ 7007.6143],
       [56097.965 ],
       [11583.585 ]], dtype=float32)

In [17]:
predictions_df = pd.DataFrame(predict, columns=['Predicted_Y'])
result_df = pd.concat([X_test_copy.reset_index(drop=True), Y_test.reset_index(drop=True), predictions_df], axis=1)
result_df.rename(columns={'charges': 'Original Y'}, inplace=True)

In [18]:
result_df

,age,sex,bmi,children,smoker,region,Original Y,Predicted_Y
0,45,female,25.175,2,no,northeast,9095.06825,10596.265625
1,36,female,30.020,0,no,northwest,5272.17580,6135.238770
2,64,female,26.885,0,yes,northwest,29330.98315,33391.238281
3,46,male,25.745,3,no,northwest,9301.89355,9237.971680
4,19,male,31.920,0,yes,northwest,33750.29180,28825.550781
...,...,...,...,...,...,...,...,...
263,63,male,35.090,0,yes,southeast,47055.53210,45926.234375
264,58,female,27.170,0,no,northwest,12222.89830,12345.850586
265,38,male,28.025,1,no,northeast,6067.12675,7007.614258
266,54,female,47.410,0,yes,southeast,63770.42801,56097.964844
267,51,female,34.200,1,no,southwest,9872.70100,11583.584961